INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
INSERT INTO reviews (restaurant_id,user_name,review_text,"date",contributions,rating) VALUES
